server:
  port: 0 #dynamic!
eureka:
  client:
    register-with-eureka: false
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: chat
        output:
          destination: chat
  application:
    name: chatter-command-bot
chatter:
  bot:
    commands:
      banner: com.example.BannerCommandHandler
      echo: com.example.EchoCommandHandler
      date: com.example.DateCommandHandler
logging:
  level:
    com.example.BannerCommandHandler: debug
---
spring:
  profiles: cloud
eureka:
  client:
    service-url:
      defaultZone: http://eureka-pws.cfapps.io/eureka/
 